deploy:
  provider: npm
  email: ntnlbg@gmail.com
  api_key:
    secure: SjWTlB9UVw1QLuawGI6C4vcigT2MXEchDcZCVsq3+dWKy3wTZuy+4t266RBf5tWF7qCIuzSEkEWmt4Ri8qaJ4WKaBFvtjhrs1HAdGXtmPkNfXvlnfODll7dj+Bw06ALMJsZ6ySndwEH15BWRuGOIu+2RiKK9OuXXNIFLbUd/d0BerPEcO5/g0RUHtB1Kwbu1BgUnXK0e4sKkAix+EpWH7vze9CXIwIz6Ry8JvM4S7mysAWmC6i55pw925IpPs2N3aDn2+KvIQ2BvI4ibUjymrdah5CvWzudS4OXQDwbBG4/A5IObvFklCEMkzdPt1jUps91gZi+6qqb+D/cV9JgZRRRlCux7+AHh4pe/yhosa8e4v80pDikaSeqPJw9cUq4ZEE4JbplIeeO8VGrk8Bg3X+D5iE7FRXk5/Vv9RG1QQuA2xxFiGN6tfWYqB7Gm99h1tsGPDdzZRCETLELVHkdoaHHrESsY8wr5qv4yaL3RWm6OwMVsvffu+2/ZLuFvJcQb3tSjyqYJMco2ZIxk0itQk0/HWOmh/JQxkNwHj8iQBs6q9W3TvlsRZoutthebIFTNm5XmskQn2N9DImcUWqf6YrsXrjOOSkrceXSYNAP4nZb3jNbydwtn9RUIKvSWhCw2XiSXm0PoVssfet6LyRvAzeCgSem/yDTFM330MbQ0vMQ=
  on:
    tags: true
    repo: natanael/ghost-editor
